### ISSUE TITLE
LueMinut missing files and actions

### ISSUE THREAD

**Issue by hsl-petrhaj** [HSLdevcom/mal-effect-calculations#72]
Lansimetron_jatke.shp
Uusimaa-kaava-2050_Pisteet.gpkg
centers_and_stations2.gpkg
centers.tsv
maapinta_ala_ja_asutut_ruudut.xlsx

Subkansiot:
MAL2023_Ve1_data_ja_info
- MAL2023_ensisijaiset_vyohykkeet_Ve1.shp ja muut
- MAL2023_ensisijaiset_vyöhykkeet_Ve1_ruudut_lisaykset.shp ja muut
- MAL2023_maankäyttö_Ve1.shp ja muut
MAL2023_vertailupohja_YKR_250m_20220210_kaikkiruudut
- MAL2023_vertailupohja_YKR_250m_20220210_kaikkiruudut.shp
aluejaot_2019_SHP
- sijoittelualueet2019.shp

polut config.xml:ssä
Results kansio esimerkki
Syöttötiedot kansio (2018 jo viitattu lue_minut tiedostossa)

Squares rds to be changed manually so that it fits the naming (ve0 -> ve0u)
zones_2040_ve0.rds hardcoded, made a copy from "u" version
links_2040_ve0.rds hardcoded, made a copy from "u" version

**Comment by johpiip** [comment]
Reviewed `LUEMINUT.txt` and fixed a couple sources. I also commited some clarifications straight to `main`'s `README.md` here: https://github.com/HSLdevcom/mal-effect-calculations/commit/8c96efa06b82ecde71bf50d11f095a8318727f35 I think some of the problems in this issue were due to older version of the scripts (when ve1 was still a thing) and also old LUEMINUT.txt which referred to older ve0 and ve1 materials but not ve2 materials. Lets test this together, and open this issue again is necessary.
